# Generated by Django 5.0.6 on 2024-06-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='upload_range',
            field=models.PositiveBigIntegerField(),
        ),
    ]
