# Generated by Django 5.0.6 on 2024-07-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_events_upload_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='key',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='upload_range',
            field=models.PositiveBigIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='eventAttender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('selfie', models.ImageField(upload_to='selfies')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attenders', to='studio.events')),
            ],
        ),
        migrations.CreateModel(
            name='selfie_matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='studio.eventattender')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.pictures')),
            ],
        ),
    ]
